#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Player Value Bets V2 — shots & shots on target (1+, 2+, 3+)

Key changes vs legacy scripts:
  • No moneyline filter — gating uses opponent shot-rank filtering instead.
  • Filters out games played against the 5 stingiest defences (shots conceded)
    unless the player's team is in the top-3 for shots for (per-league ranks
    generated by compute_team_shot_ranks.py).
  • Supports four markets with a single price gate: 1+ shot, 1+ SOT, 2+ shots,
    3+ shots — all require price >= MIN_DEC_PRICE (default 1.72).

Form logic (uses filtered series):
  • FWD/MID 1+ shot: last 5 all >= 1.
  • DEF 1+ shot: last 5 all >= 1 AND (avg of last 10 >= 0.7 OR >=2 shots in at
    least 2 of the last 5).
  • Global 1+ shot: 8/10 hits, or if <10 games then 6/7 hits.
  • 2+ shots: 5/5 OR 7/10 with >= 2 shots.
  • 3+ shots: 5/5 OR 7/10 with >= 3 shots.
  • 1+ SOT: same trigger set as 1+ shots but using SOT series.

Inputs:
  • Player shots:            data/player_shots/by_league/{league_id}.json
  • Player shots on target:  data/player_shots_on_target/by_league/{league_id}.json
  • Fixtures (for opponent lookup): data/fixtures/{league_id}.json
  • Odds (Bet365 aggregated): data/odds/b365/{league_id}.json
  • Team shot ranks:         data/value_bets/Player_value_bets_V2/team_shot_ranks/{league_id}.json

Output:
  • data/value_bets/Player_value_bets_V2/value_singles_shots_v2.txt

Env (optional):
  • MIN_DEC_PRICE  default 1.72
  • LEAGUE_IDS     comma-separated list; defaults to standard set
"""

import json
import math
import os
import re
import unicodedata
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple


# ---------- Config / paths ----------
MIN_PRICE = float(os.getenv("MIN_DEC_PRICE", "1.72"))
DEFAULT_LEAGUES = [301, 384, 387, 564, 567, 600, 8, 82, 9]
LEAGUE_IDS: List[int] = [
    int(x)
    for x in (os.getenv("LEAGUE_IDS") or ",".join(map(str, DEFAULT_LEAGUES))).split(",")
    if x.strip()
]

ROOT = Path(".")
PS_DIR = ROOT / "data" / "player_shots" / "by_league"
SOT_DIR = ROOT / "data" / "player_shots_on_target" / "by_league"
FIX_DIR = ROOT / "data" / "fixtures"
ODDS_DIR = ROOT / "data" / "odds" / "b365"
RANK_DIR = ROOT / "data" / "value_bets" / "Player_value_bets_V2" / "team_shot_ranks"
OUT_DIR = ROOT / "data" / "value_bets" / "Player_value_bets_V2"
OUT_DIR.mkdir(parents=True, exist_ok=True)
OUT_FILE = OUT_DIR / "value_singles_shots_v2.txt"

MARKET_PLAYER_SHOTS = 268
MARKET_PLAYER_SOT = 267


# ---------- IO helpers ----------
def _load_json(path: Path) -> Optional[dict]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def _as_float(x) -> Optional[float]:
    try:
        return float(str(x))
    except Exception:
        return None


# ---------- string / name helpers (borrowed from legacy scripts) ----------
SUFFIXES = {"jr", "junior", "sr", "senior", "ii", "iii", "iv", "filho", "neto"}
SURNAME_PREFIXES = {"da", "de", "del", "der", "di", "dos", "du", "la", "le", "van", "von", "bin", "al"}
GENERIC_TOK = {
    "fc",
    "cf",
    "afc",
    "sc",
    "cd",
    "ud",
    "ac",
    "as",
    "ss",
    "ssc",
    "us",
    "uc",
    "rc",
    "rcd",
    "ca",
    "the",
    "club",
    "de",
    "del",
    "la",
    "las",
    "los",
    "calcio",
    "united",
    "city",
    "saint",
    "st",
    "bk",
}


def strip_accents(s: str) -> str:
    return "".join(c for c in unicodedata.normalize("NFD", s or "") if unicodedata.category(c) != "Mn")


def norm_spaces(s: str) -> str:
    return re.sub(r"\s+", " ", s or "").strip()


def norm(s: str) -> str:
    s = strip_accents(s or "").lower()
    s = re.sub(r"[^\w\s\.-]", " ", s)
    return norm_spaces(s)


def cleanup_label(label: str) -> str:
    return re.sub(r"(?:\s*\([^)]*\))+$", "", label or "").strip()


def person_part_from_option(label: str) -> str:
    s = cleanup_label(label or "")
    m = re.split(r"\b(?:-?\s*over|-?\s*under|\s+o\/u|\s+o\d+|\s+u\d+)\b", s, flags=re.IGNORECASE)
    return m[0].strip() if m else s


def drop_suffixes(parts: List[str]) -> List[str]:
    out = list(parts)
    while out and re.sub(r"[^\w]+", "", out[-1]).lower() in SUFFIXES:
        out = out[:-1]
    return out


def split_name_tokens(name: str) -> List[str]:
    return [p for p in norm(name).replace("-", " ").split() if p]


def surname_tokens(parts: List[str]) -> List[str]:
    parts = drop_suffixes(parts)
    if not parts:
        return []
    if len(parts) >= 2 and parts[-2] in SURNAME_PREFIXES:
        return parts[-2:]
    return parts[-1:]


def first_initial(parts: List[str]) -> Optional[str]:
    parts = drop_suffixes(parts)
    for p in parts[:-1]:
        ch = p[:1]
        if ch:
            return ch
    return None


def name_variants(full_name: str) -> List[str]:
    if not full_name:
        return []
    parts = split_name_tokens(full_name)
    if not parts:
        return []
    sur = " ".join(surname_tokens(parts))
    init = first_initial(parts)
    full = " ".join(parts)
    out = {full, sur}
    if init:
        out.add(f"{init}. {sur}")
        out.add(f"{init} {sur}")
    out.add(f"{sur} {init or ''}".strip())
    return sorted({norm(o).replace(".", "") for o in out if o})


def aliases_from_record(rec: dict) -> List[str]:
    names: List[str] = []
    for k in ("name", "player_name", "player", "short_name", "common_name", "display_name", "full_name", "known_as"):
        v = rec.get(k)
        if isinstance(v, str) and v.strip():
            names.append(v.strip())
    seen, uniq = set(), []
    for n in names:
        key = norm(n)
        if key not in seen:
            seen.add(key)
            uniq.append(n)
    out: List[str] = []
    for n in uniq:
        out.extend(name_variants(n))
    seen2, uniq2 = set(), []
    for a in out:
        if a not in seen2:
            seen2.add(a)
            uniq2.append(a)
    return uniq2


def label_matches_aliases(option_label: str, aliases: Iterable[str]) -> bool:
    lab = norm(person_part_from_option(option_label)).replace(".", "")
    if not lab:
        return False
    lab_tokens = set(lab.split())
    for alias in aliases:
        atoks = set(alias.split())
        if alias == lab or (atoks and (atoks.issubset(lab_tokens) or lab_tokens.issubset(atoks))):
            return True
        a_parts = alias.split()
        a_sur = a_parts[-2:] if len(a_parts) >= 2 and a_parts[-2] in SURNAME_PREFIXES else a_parts[-1:]
        if set(a_sur).issubset(lab_tokens):
            if len(a_parts) >= 2 and len(a_parts[0]) == 1:
                if a_parts[0] in lab_tokens or lab.startswith(a_parts[0] + " "):
                    return True
                continue
            return True
    return False


def team_tokens(name: str):
    return {t for t in norm(name).split() if t not in GENERIC_TOK}


def team_names_match(a: str, b: str) -> bool:
    if not a or not b:
        return False
    ta, tb = team_tokens(a), team_tokens(b)
    if not ta or not tb:
        return False
    if ta == tb or ta.issubset(tb) or tb.issubset(ta):
        return True
    inter = ta & tb
    union = ta | tb
    return (len(inter) / max(1, len(union)) >= 0.5) or (len(inter) >= 2)


# ---------- fixture helpers ----------
def _fixture_map(league_id: int) -> Dict[int, dict]:
    out: Dict[int, dict] = {}
    blob = _load_json(FIX_DIR / f"{league_id}.json") or {}
    for fx in blob.get("fixtures", []) or []:
        fid = fx.get("id")
        if not isinstance(fid, int):
            continue
        parts = fx.get("participants") or []
        home_id = away_id = None
        home_name = away_name = ""
        if isinstance(parts, list):
            for p in parts:
                pid = p.get("id")
                loc = (p.get("meta", {}) or {}).get("location", "").lower()
                if loc.startswith("home"):
                    home_id, home_name = int(pid or 0), p.get("name") or ""
                elif loc.startswith("away"):
                    away_id, away_name = int(pid or 0), p.get("name") or ""
        out[fid] = {
            "home_id": home_id,
            "away_id": away_id,
            "home_name": home_name,
            "away_name": away_name,
        }
    return out


def opponent_for(team_id: int, fixture_id: int, fmap: Dict[int, dict]) -> Optional[int]:
    fx = fmap.get(fixture_id)
    if not fx:
        return None
    if team_id == fx.get("home_id"):
        return fx.get("away_id")
    if team_id == fx.get("away_id"):
        return fx.get("home_id")
    return None


# ---------- shot rank helpers ----------
def load_shot_rank_sets(league_id: int) -> Tuple[set, set]:
    """Returns (stingy_team_ids, top_shooters_ids)."""
    blob = _load_json(RANK_DIR / f"{league_id}.json") or {}
    stingy = {int(r.get("team_id")) for r in (blob.get("shots_conceded_rank") or [])[:5] if r.get("team_id") is not None}
    top_for = {int(r.get("team_id")) for r in (blob.get("shots_for_rank") or [])[:3] if r.get("team_id") is not None}
    return stingy, top_for


# ---------- series filtering ----------
def filtered_series(values: List[Any], fixture_ids: List[Any], team_id: int, fmap: Dict[int, dict], stingy: set, top_for: set) -> List[int]:
    out: List[int] = []
    for val, fid in zip(values or [], fixture_ids or []):
        try:
            v = int(val)
        except Exception:
            continue
        try:
            fid_int = int(fid)
        except Exception:
            fid_int = None
        if fid_int:
            opp = opponent_for(team_id, fid_int, fmap)
            if opp in stingy and team_id not in top_for:
                continue
        out.append(v)
    return out


def take(series: List[int], n: int) -> List[int]:
    return [int(x) for x in series[:n] if isinstance(x, int)]


def hits(series: List[int], threshold: int, n: int) -> int:
    return sum(1 for x in take(series, n) if x >= threshold)


# ---------- form gates ----------
def qualifies_fwd_mid(series: List[int]) -> bool:
    return len(take(series, 5)) >= 5 and all(x >= 1 for x in take(series, 5))


def qualifies_def(series: List[int]) -> bool:
    first5 = take(series, 5)
    if len(first5) < 5 or not all(x >= 1 for x in first5):
        return False
    last10 = take(series, 10)
    if last10 and (sum(last10) / len(last10)) >= 0.7:
        return True
    if len(first5) >= 5 and sum(1 for x in first5 if x >= 2) >= 2:
        return True
    return False


def qualifies_global(series: List[int]) -> bool:
    if len(take(series, 10)) >= 10 and hits(series, 1, 10) >= 8:
        return True
    if len(take(series, 7)) >= 7 and hits(series, 1, 7) >= 6:
        return True
    return False


def qualifies_line(series: List[int], line: int) -> Optional[str]:
    if len(take(series, 5)) >= 5 and hits(series, line, 5) == 5:
        return "5/5"
    if len(take(series, 10)) >= 10 and hits(series, line, 10) >= 7:
        return "7/10"
    return None


# ---------- odds parsing ----------
def best_price_for_line(odds_rows: List[dict], player_rec: dict, market_id: int, target_label: str) -> Optional[float]:
    aliases = aliases_from_record(player_rec)
    prices: List[float] = []
    for row in odds_rows or []:
        if int(row.get("market_id") or 0) != market_id:
            continue
        label = str(row.get("label") or "").strip()
        if label and not math.isclose(_as_float(label) or 0.0, _as_float(target_label) or 0.0, abs_tol=1e-6):
            continue
        name_fields = [row.get("name", ""), row.get("total", ""), row.get("original_label", ""), row.get("description", ""), row.get("header", "")]
        if not any(label_matches_aliases(str(nf), aliases) for nf in name_fields):
            continue
        price = _as_float(row.get("value"))
        if price is None:
            continue
        prices.append(price)
    if not prices:
        return None
    return min(prices)


# ---------- data loading helpers ----------
def load_player_rows(path: Path, values_key: str) -> List[dict]:
    blob = _load_json(path) or {}
    players = blob.get("players") or blob.get("rows") or blob.get("data") or []
    out: List[dict] = []
    for rec in players:
        vals = rec.get(values_key) or []
        fixture_ids = rec.get("fixture_ids") or []
        if not isinstance(vals, list) or not isinstance(fixture_ids, list):
            continue
        out.append(rec)
    return out


# ---------- candidate building ----------
def build_candidates(league_id: int) -> Dict[str, List[dict]]:
    fmap = _fixture_map(league_id)
    stingy, top_for = load_shot_rank_sets(league_id)

    shot_rows = load_player_rows(PS_DIR / f"{league_id}.json", "shots_last_n")
    sot_rows = load_player_rows(SOT_DIR / f"{league_id}.json", "on_target_last_n")

    by_player: Dict[int, dict] = {}
    for rec in shot_rows:
        pid = rec.get("player_id") or (rec.get("name") or rec.get("player"))
        if pid in by_player:
            continue
        team_id = int(rec.get("team_id") or 0)
        filt = filtered_series(rec.get("shots_last_n") or [], rec.get("fixture_ids") or [], team_id, fmap, stingy, top_for)
        by_player[pid] = {
            "league_id": league_id,
            "team_id": team_id,
            "team_name": rec.get("team") or rec.get("team_name") or "",
            "player": rec.get("name") or rec.get("player_name") or rec.get("player") or "",
            "position": (rec.get("position_tag") or rec.get("position") or rec.get("pos") or "").upper(),
            "shots_filtered": filt,
            "orig_series": rec.get("shots_last_n") or [],
            "fixture_ids": rec.get("fixture_ids") or [],
            "_rec": dict(rec, name=rec.get("name") or rec.get("player_name") or rec.get("player")),
        }

    for rec in sot_rows:
        pid = rec.get("player_id") or (rec.get("name") or rec.get("player"))
        if pid not in by_player:
            continue
        team_id = int(rec.get("team_id") or 0)
        filt = filtered_series(rec.get("on_target_last_n") or [], rec.get("fixture_ids") or [], team_id, fmap, stingy, top_for)
        by_player[pid]["sot_filtered"] = filt
        by_player[pid]["sot_orig"] = rec.get("on_target_last_n") or []
        by_player[pid]["_rec_sot"] = dict(rec, name=rec.get("name") or rec.get("player_name") or rec.get("player"))

    buckets: Dict[str, List[dict]] = {"1+": [], "1+_sot": [], "2+": [], "3+": []}
    for pdata in by_player.values():
        series = pdata["shots_filtered"]
        pos = pdata.get("position", "")
        # 1+ shots triggers
        triggers: List[str] = []
        if pos in {"FWD", "MID"} and qualifies_fwd_mid(series):
            triggers.append("1+ (FWD/MID 5/5)")
        if pos == "DEF" and qualifies_def(series):
            triggers.append("1+ (DEF 5/5 + avg)")
        if qualifies_global(series):
            triggers.append("1+ (8/10 or 6/7)")
        if triggers:
            buckets["1+"].append({**pdata, "triggers": triggers})

        # 2+ shots
        tag2 = qualifies_line(series, 2)
        if tag2:
            buckets["2+"].append({**pdata, "triggers": [f"2+ ({tag2})"], "line": 2})

        # 3+ shots
        tag3 = qualifies_line(series, 3)
        if tag3:
            buckets["3+"].append({**pdata, "triggers": [f"3+ ({tag3})"], "line": 3})

        # 1+ SOT
        sot_series = pdata.get("sot_filtered")
        if sot_series is not None:
            sot_triggers: List[str] = []
            if pos in {"FWD", "MID"} and qualifies_fwd_mid(sot_series):
                sot_triggers.append("1+ SOT (FWD/MID 5/5)")
            if pos == "DEF" and qualifies_def(sot_series):
                sot_triggers.append("1+ SOT (DEF 5/5 + avg)")
            if qualifies_global(sot_series):
                sot_triggers.append("1+ SOT (8/10 or 6/7)")
            if sot_triggers:
                buckets["1+_sot"].append({**pdata, "triggers": sot_triggers})

    return buckets


# ---------- fixture match for pricing ----------
def fixture_lookup(league_id: int) -> Dict[int, dict]:
    fmap = _fixture_map(league_id)
    out: Dict[int, dict] = {}
    for fid, fx in fmap.items():
        out[fid] = fx
    return out


def find_fixture_odds(team_id: int, league_fixture_map: Dict[int, dict], odds_fixtures: List[dict]) -> Optional[Tuple[dict, dict]]:
    for fx in odds_fixtures or []:
        fid = fx.get("fixture_id")
        if not isinstance(fid, int):
            continue
        meta = league_fixture_map.get(fid)
        if not meta:
            continue
        if team_id in (meta.get("home_id"), meta.get("away_id")):
            return fx, meta
    return None


# ---------- pricing + rendering ----------
def render_group(name: str, picks: List[dict], lines: List[str]) -> None:
    lines.append(f"===== {name} (count: {len(picks)}) =====")
    if not picks:
        lines.append("  — none —")
        lines.append("")
        return
    picks.sort(key=lambda r: (-r.get("price", 0), r.get("player", "")))
    for p in picks:
        ser = ",".join(map(str, take(p.get("shots_filtered", []), 10)))
        out_line = (
            f" • {p['player']} [{p.get('position','')}] — {p.get('team_name','')} | {p.get('fixture_name','')} @ {p.get('kickoff','')} | "
            f"{p.get('market_label','')} @ {p['price']:.2f} | triggers: {', '.join(p['triggers'])} | series: {ser}"
        )
        lines.append(out_line)
    lines.append("")


def main() -> None:
    odds_by_league: Dict[int, dict] = {lid: (_load_json(ODDS_DIR / f"{lid}.json") or {}) for lid in LEAGUE_IDS}
    fixture_maps: Dict[int, Dict[int, dict]] = {lid: fixture_lookup(lid) for lid in LEAGUE_IDS}

    all_picks: Dict[str, List[dict]] = {"1+": [], "1+_sot": [], "2+": [], "3+": []}

    for lid in LEAGUE_IDS:
        buckets = build_candidates(lid)
        odds_blob = odds_by_league.get(lid) or {}
        odds_fixtures = odds_blob.get("fixtures") or []
        fx_map = fixture_maps.get(lid) or {}

        for market_key, market_id, label in (
            ("1+", MARKET_PLAYER_SHOTS, "0.5"),
            ("1+_sot", MARKET_PLAYER_SOT, "0.5"),
            ("2+", MARKET_PLAYER_SHOTS, "1.5"),
            ("3+", MARKET_PLAYER_SHOTS, "2.5"),
        ):
            for cand in buckets.get(market_key, []):
                found = find_fixture_odds(cand.get("team_id") or 0, fx_map, odds_fixtures)
                if not found:
                    continue
                fx_odds, meta = found
                price = best_price_for_line(fx_odds.get("odds") or [], cand.get("_rec") if market_key != "1+_sot" else cand.get("_rec_sot", cand.get("_rec")), market_id, label)
                if price is None or price < MIN_PRICE:
                    continue
                pick = {
                    **cand,
                    "price": price,
                    "fixture_name": fx_odds.get("name") or "",
                    "kickoff": fx_odds.get("starting_at") or "",
                    "market_label": {"1+": "O0.5 shots", "1+_sot": "O0.5 SOT", "2+": "O1.5 shots", "3+": "O2.5 shots"}[market_key],
                }
                all_picks[market_key].append(pick)

    ts = os.popen("date -u +%Y-%m-%dT%H:%M:%SZ").read().strip()
    lines: List[str] = []
    lines.append(f"Generated at (UTC): {ts}")
    lines.append(
        "Opponent filter: drop games vs top-5 stingiest by shots conceded unless player's team is top-3 for shots for (per league)."
    )
    lines.append(f"Price gate: >= {MIN_PRICE:.2f}; Markets: 1+ shot, 1+ SOT, 2+ shots, 3+ shots (Bet365 player markets)")
    lines.append("")

    render_group("1+ shots", all_picks["1+"], lines)
    render_group("1+ SOT", all_picks["1+_sot"], lines)
    render_group("2+ shots", all_picks["2+"], lines)
    render_group("3+ shots", all_picks["3+"], lines)

    OUT_FILE.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
