#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Build a goals post from local JSON only.

Inputs (already generated by your other jobs):
  - data/fixtures/by_league/*.json            (or data/fixtures/*.json)
      -> upcoming fixtures with participants [{id,name,meta.location}]
  - data/team_stats/by_league/*.json
      -> for each team: goals_last_n
  - data/team_opponent_stats/by_league/*.json
      -> for each team: opp_goals_last_n

Logic:
  - For each team, compute last-10 rates from (goals_last_n[i] + opp_goals_last_n[i]):
      * Over 2.5 rate: (team_goals + opp_goals) >= 3
      * BTTS rate    : (team_goals >= 1 and opp_goals >= 1)
      * Over 1.5 for-team: (team_goals >= 2)

  - Shortlist 1: Combined Over 2.5 (show *only* fixtures where BOTH teams O2.5 ≥ O25_BOTH_THRESHOLD, default 70).
    Sort by combined = mean(home%, away%) desc. Display "Home (H%) vs Away (A%)"

  - Shortlist 2: BTTS (same gate but for BTTS).

  - List 3: Single-team O1.5 ≥ threshold (default 70) — show unique team names only
    sorted by their own O1.5% desc (no opponent in this list).

Environment (optional):
  O25_BOTH_THRESHOLD=70
  BTTS_BOTH_THRESHOLD=70
  SINGLE_TEAM_O15_THRESHOLD=70
  LAST_N=10
  MIN_SAMPLES=6
  OUTPUT_PATH=posts/over25_matches.md
"""

import os
import json
import math
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# ---------------- Config ----------------
O25_BOTH_THRESHOLD = float(os.getenv("O25_BOTH_THRESHOLD", "70"))
BTTS_BOTH_THRESHOLD = float(os.getenv("BTTS_BOTH_THRESHOLD", "70"))
SINGLE_TEAM_O15_THRESHOLD = float(os.getenv("SINGLE_TEAM_O15_THRESHOLD", "70"))

LAST_N = int(os.getenv("LAST_N", "10"))
MIN_SAMPLES = int(os.getenv("MIN_SAMPLES", "6"))

OUTPUT_PATH = Path(os.getenv("OUTPUT_PATH", "posts/over25_matches.md"))

# ---------------- IO helpers ----------------
def _load_json(path: Path) -> Optional[dict]:
    if not path.is_file():
        return None
    try:
        with path.open("r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None

def load_fixtures() -> List[dict]:
    """Prefer data/fixtures/by_league/*.json; else fall back to data/fixtures/*.json."""
    base = Path("data/fixtures")
    by_league = base / "by_league"
    out: List[dict] = []

    def take(p: Path):
        blob = _load_json(p)
        if not blob:
            return
        if isinstance(blob, dict) and "fixtures" in blob:
            out.extend([fx for fx in blob["fixtures"] if fx and fx.get("participants")])
        elif isinstance(blob, list):
            out.extend([fx for fx in blob if fx and fx.get("participants")])

    if by_league.is_dir():
        for p in sorted(by_league.glob("*.json")):
            take(p)
    elif base.is_dir():
        for p in sorted(base.glob("*.json")):
            if p.name == "latest.json":
                # latest.json contains all fixtures too — include it as well
                take(p)
            else:
                take(p)
    # keep unique by id
    seen = set()
    uniq = []
    for fx in out:
        fid = fx.get("id")
        if fid and fid not in seen:
            uniq.append(fx)
            seen.add(fid)
    return uniq

def load_team_maps() -> Tuple[Dict[int, dict], Dict[int, dict]]:
    """
    Return:
      team_stats[team_id] -> {"team_name": str, "goals": [int,...]}
      opp_stats [team_id] -> {"opp_goals": [int,...]}
    """
    team_stats: Dict[int, dict] = {}
    opp_stats: Dict[int, dict] = {}

    base_team = Path("data/team_stats/by_league")
    base_opp  = Path("data/team_opponent_stats/by_league")

    # team stats (goals_last_n)
    if base_team.is_dir():
        for p in sorted(base_team.glob("*.json")):
            blob = _load_json(p) or {}
            for row in (blob.get("teams") or []):
                tid = row.get("team_id")
                if not isinstance(tid, int):
                    continue
                nm = (row.get("team_name") or "").strip() or f"Team {tid}"
                goals = row.get("goals_last_n") or []
                if isinstance(goals, list) and goals:
                    team_stats[tid] = {"team_name": nm, "goals": [int(x) for x in goals]}

    # opponent stats (opp_goals_last_n)
    if base_opp.is_dir():
        for p in sorted(base_opp.glob("*.json")):
            blob = _load_json(p) or {}
            for row in (blob.get("teams") or []):
                tid = row.get("team_id")
                if not isinstance(tid, int):
                    continue
                og = row.get("opp_goals_last_n") or []
                if isinstance(og, list) and og:
                    opp_stats[tid] = {"opp_goals": [int(x) for x in og]}

    return team_stats, opp_stats

# ---------------- Rate calculators ----------------
def _paired_series(team_row: dict, opp_row: dict) -> List[Tuple[int,int]]:
    """Align goals + opp_goals up to LAST_N and build (gf, ga) pairs latest->older."""
    gf = list(team_row.get("goals") or [])
    ga = list(opp_row.get("opp_goals") or [])
    m = min(len(gf), len(ga), LAST_N)
    return [(int(gf[i]), int(ga[i])) for i in range(m)]

def over25_rate(team_row: dict, opp_row: dict) -> Optional[float]:
    pairs = _paired_series(team_row, opp_row)
    if len(pairs) < MIN_SAMPLES:
        return None
    hits = sum(1 for gf, ga in pairs if (gf + ga) >= 3)
    return 100.0 * hits / len(pairs)

def btts_rate(team_row: dict, opp_row: dict) -> Optional[float]:
    pairs = _paired_series(team_row, opp_row)
    if len(pairs) < MIN_SAMPLES:
        return None
    hits = sum(1 for gf, ga in pairs if gf >= 1 and ga >= 1)
    return 100.0 * hits / len(pairs)

def over15_scored_rate(team_row: dict) -> Optional[float]:
    gf = list(team_row.get("goals") or [])[:LAST_N]
    if len(gf) < MIN_SAMPLES:
        return None
    hits = sum(1 for x in gf if int(x) >= 2)
    return 100.0 * hits / len(gf)

# ---------------- Fixture parsing helpers ----------------
def pick_home_away(parts: List[dict]) -> Tuple[Optional[dict], Optional[dict]]:
    home = next((p for p in parts if (p.get("meta") or {}).get("location") == "home"), None)
    away = next((p for p in parts if (p.get("meta") or {}).get("location") == "away"), None)
    # fallback order if meta missing
    if not home or not away:
        parts2 = [p for p in parts if isinstance(p.get("id"), int)]
        if len(parts2) >= 2:
            home = home or parts2[0]
            away = away or parts2[1]
    return home, away

# ---------------- Main build ----------------
def main():
    fixtures = load_fixtures()
    team_map, opp_map = load_team_maps()

    # Precompute per-team metrics
    team_o25: Dict[int, float] = {}
    team_btts: Dict[int, float] = {}
    team_o15: Dict[int, float] = {}
    team_name: Dict[int, str] = {}

    # build for all teams present in stats (fast)
    for tid, trow in team_map.items():
        team_name[tid] = trow.get("team_name") or f"Team {tid}"
        o15 = over15_scored_rate(trow)
        if o15 is not None:
            team_o15[tid] = o15
        # need opp row to compute o25/btts
        orow = opp_map.get(tid)
        if orow:
            o25 = over25_rate(trow, orow)
            bts = btts_rate(trow, orow)
            if o25 is not None:
                team_o25[tid] = o25
            if bts is not None:
                team_btts[tid] = bts

    # Build lists from fixtures only (so we don’t list teams without a game)
    combined_o25_entries: List[dict] = []
    btts_entries: List[dict] = []
    single_o15_teams: Dict[int, float] = {}  # dedupe by team

    for fx in fixtures:
        parts = fx.get("participants") or []
        home, away = pick_home_away(parts)
        if not (home and away):
            continue
        hid, aid = home.get("id"), away.get("id")
        if not isinstance(hid, int) or not isinstance(aid, int):
            continue

        hname = team_name.get(hid) or (home.get("name") or f"Team {hid}")
        aname = team_name.get(aid) or (away.get("name") or f"Team {aid}")

        # O2.5 — require both teams to have individual O2.5 >= threshold
        hpct_o25 = team_o25.get(hid)
        apct_o25 = team_o25.get(aid)
        if hpct_o25 is not None and apct_o25 is not None:
            if hpct_o25 >= O25_BOTH_THRESHOLD and apct_o25 >= O25_BOTH_THRESHOLD:
                combined = (hpct_o25 + apct_o25) / 2.0
                combined_o25_entries.append({
                    "home_id": hid, "away_id": aid,
                    "home_name": hname, "away_name": aname,
                    "hpct": hpct_o25, "apct": apct_o25, "combined": combined
                })

        # BTTS — require both teams to have BTTS >= threshold
        hpct_btts = team_btts.get(hid)
        apct_btts = team_btts.get(aid)
        if hpct_btts is not None and apct_btts is not None:
            if hpct_btts >= BTTS_BOTH_THRESHOLD and apct_btts >= BTTS_BOTH_THRESHOLD:
                combined_btts = (hpct_btts + apct_btts) / 2.0
                btts_entries.append({
                    "home_id": hid, "away_id": aid,
                    "home_name": hname, "away_name": aname,
                    "hpct": hpct_btts, "apct": apct_btts, "combined": combined_btts
                })

        # Single-team O1.5 list (teams with upcoming fixtures)
        hpct_o15 = team_o15.get(hid)
        if hpct_o15 is not None and hpct_o15 >= SINGLE_TEAM_O15_THRESHOLD:
            single_o15_teams[hid] = hpct_o15
        apct_o15 = team_o15.get(aid)
        if apct_o15 is not None and apct_o15 >= SINGLE_TEAM_O15_THRESHOLD:
            single_o15_teams[aid] = apct_o15

    # Sort outputs
    combined_o25_entries.sort(key=lambda x: (-x["combined"], -x["hpct"], -x["apct"], x["home_name"], x["away_name"]))
    btts_entries.sort(key=lambda x: (-x["combined"], -x["hpct"], -x["apct"], x["home_name"], x["away_name"]))
    single_o15_sorted = sorted(single_o15_teams.items(), key=lambda kv: (-kv[1], team_name.get(kv[0], f"Team {kv[0]}")))

    # Render
    min_needed = math.ceil(SINGLE_TEAM_O15_THRESHOLD / 100.0 * LAST_N)
    lines: List[str] = []
    lines.append("I’ve collated a high-probability goals list based on stats from their last 10 games.")
    lines.append("")
    lines.append("Leave a like if you find these useful.")
    lines.append("")

    # Combined Over 2.5 (both teams gate)
    lines.append("📊Combined over 2.5 goals >70%📊")
    lines.append("(Both teams’ matches have had at least 2.5 goals in 70%+ of their last 10)")
    lines.append("")
    if combined_o25_entries:
        for e in combined_o25_entries:
            lines.append(f"{e['home_name']} ({e['hpct']:.0f}%) vs {e['away_name']} ({e['apct']:.0f}%)")
    else:
        lines.append("(No fixtures cleared the threshold based on the latest files.)")
    lines.append("")

    # BTTS (both teams gate)
    lines.append("📊Both Teams To Score (BTTS) >70%📊")
    lines.append("(Both teams’ matches have seen goals at both ends in 70%+ of their last 10)")
    lines.append("")
    if btts_entries:
        for e in btts_entries:
            lines.append(f"{e['home_name']} ({e['hpct']:.0f}%) vs {e['away_name']} ({e['apct']:.0f}%)")
    else:
        lines.append("(No fixtures cleared the threshold based on the latest files.)")
    lines.append("")

    # Single-team O1.5
    lines.append(f"📈 Single-team over 1.5 ≥{SINGLE_TEAM_O15_THRESHOLD:.0f}%📈")
    lines.append(f"(Teams who have scored 2+ goals in at least {min_needed} of their last {LAST_N})")
    lines.append("")
    if single_o15_sorted:
        for tid, pct in single_o15_sorted:
            nm = team_name.get(tid, f"Team {tid}")
            lines.append(f"{nm} ({pct:.0f}%)")
    else:
        lines.append("(No teams cleared the threshold based on the latest files.)")
    lines.append("")

    # Write
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")
    print("")
    print("\n".join(lines))

if __name__ == "__main__":
    main()
